// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oonmmzbxajkcszzksfpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vbm1temJ4YWprY3N6emtzZnBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMDQyNzcsImV4cCI6MjA1NTc4MDI3N30.xdT_a7VmjDtmg78DoG9SQrIssaGW-GxTkw3KnIVA_Vw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);